# Generated by Django 3.2.7 on 2023-12-05 15:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL)
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appVersion_ema', models.TextField(max_length=10)),
                ('applicationType', models.TextField(max_length=10)),
                ('deviceBrand_ema', models.TextField(max_length=10)),
                ('deviceModel_ema', models.TextField(max_length=10)),
                ('osVersion_ema', models.TextField(max_length=10)),
                ('deviceid_ema', models.TextField(max_length=500)),
                ('status_ema', models.IntegerField(default=0)),
                ('pushNotification_token_ema', models.TextField(max_length=1000)),
                ('studyId', models.TextField(max_length=500)),
                ('time_joined_ema', models.DateTimeField()),
                ('time_left_ema', models.DateTimeField()),
                ('username', models.TextField(max_length=100)),
                ('study_duration', models.IntegerField(default=0)),
                ('active_labeling', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('deviceBrand', models.TextField(max_length=10)),
                ('deviceModel', models.TextField(max_length=10)),
                ('osVersion', models.TextField(max_length=10)),
                ('deviceid', models.TextField(max_length=500)),
                ('pushNotification_token', models.TextField(max_length=1000)),
                ('time_joined', models.DateTimeField()),
                ('time_left', models.DateTimeField()),
                ('timejoined_timezone', models.TextField(max_length=50)),
                ('timeZoneOffSetMinutes', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('topN', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_test', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500)),
                ('duration', models.IntegerField(default=0)),
                ('numberOfSubjects', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('enrolled_subjects', models.CharField(blank=True, max_length=10000, null=True)),
                ('createdDate', models.DateTimeField(default=datetime.now().astimezone())),
                ('passive_monitoring', models.BooleanField(default=False)),
                ('frequency', models.IntegerField(choices=[(50, '50 hz'), (100, '100 Hz'), (150, '150 Hz'), (200, '200 Hz')], default=50)),
                ('sensor_list', models.CharField(choices=[('accelerometer', 'accelerometer'), ('activity', 'activity'), ('application_usage', 'application usage'), ('barometer', 'barometer'), ('gravity_sensor', 'gravity sensor'), ('gyroscope', 'gyroscope'), ('location', 'location'), ('magnetic_sensor', 'magnetic sensor'), ('rotation_vector', 'rotation vector'), ('linear_acceleration', 'linear acceleration'), ('lockUnlock', 'lockUnlock'), ('voice', 'voice')], default='', max_length=150)),
                ('labeling', models.IntegerField(choices=[(0, 'No labeling '), (1, 'Active labeling'), (2, 'Manual active labeling'), (3, 'Partial active labeling')], default=0)),
                ('ecological_momentary_assessment', models.BooleanField(default=False)),
                ('images', models.CharField(blank=True, default='', max_length=500)),
                ('closed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jdash.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subText', models.TextField(blank=True, max_length=1000)),
                ('type', models.IntegerField(choices=[(1, 'Single Choose'), (2, 'Multiple Choose'), (3, 'Free Text'), (4, 'Free Number'), (5, 'Sliding'), (6, 'Time'), (7, 'Date'), (8, 'Time and Date'), (9, 'Duration')])),
                ('category', models.IntegerField(default=1)),
                ('imageURL', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('frequency', models.IntegerField(default=0)),
                ('clockTime', models.IntegerField(default=480)),
                ('nextDayToAnswer', models.IntegerField(default=1)),
                ('deactivateOnAnswer', models.CharField(blank=True, max_length=5)),
                ('deactivateOnDate', models.IntegerField(default=0)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jdash.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerText', models.CharField(max_length=200)),
                ('answerValue', models.FloatField(default=0.1)),
                ('defaultValue', models.FloatField(default=0.1)),
                ('stepSize', models.FloatField(default=0.1)),
                ('minValue', models.FloatField(default=0.1)),
                ('maxValue', models.FloatField(default=0.1)),
                ('minText', models.CharField(blank=True, max_length=100)),
                ('maxText', models.CharField(blank=True, max_length=100)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jdash.question')),
            ],
        ),
    ]
