"""
Django settings for admin project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import datetime
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
JDASH_DIR = BASE_DIR / "jdash"
SECRETS_DIR = BASE_DIR / "secrets"

load_dotenv(BASE_DIR / "secrets" / "tokens.env")

LOG_FILENAME = os.path.join(os.getenv("LOG_DIR", ''),
                f"debug_{datetime.datetime.now().strftime('%Y-%m-%d')}.log")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    "jdash.inm7.de,jutrack.inm7.de,127.0.0.1,localhost"
).split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    "django_browser_reload",
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'dpd_static_support',
    'jdash.apps.jdashConfig', 
    'auditlog',
]

MIDDLEWARE = [
    'jdash.middleware.ThreadLocalMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'jdash.maintenance_middleware.MaintenanceModeMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

ROOT_URLCONF = 'admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'admin.wsgi.application'
ASGI_APPLICATION = 'admin.routing.application'

CRISPY_TEMPLATE_PACK = 'bootstap5'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        'NAME': os.environ['DB_NAME'],
        "USER": os.environ["DB_USER"],
        "PASSWORD": os.environ["DB_PASSWORD"],
        "HOST": os.environ["DB_HOST"],
        "PORT": os.environ["DB_PORT"],
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'username_filter': {
            '()': 'jdash.logging_filters.UsernameLoggingFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {username} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
        },
    },
    
    'handlers': {
        'file': {
            'level':  'INFO',  # key part!
            'class': 'logging.FileHandler',
            'filename': LOG_FILENAME,
            'formatter': 'verbose',
            'filters': ['username_filter'],
        },
        
    },

    'loggers': {
        'django': {  # root logger: catches all
            'handlers': ['file'],
            'level':  'INFO',  # match the handler
            'propagate': True,
        },
        
    },

}
SSH_RUNTIME_DIR = os.getenv("SSH_RUNTIME_DIR", "")
MAINTENANCE_MODE = os.environ.get("MAINTENANCE_MODE", "False").lower() == "true"
MAINTENANCE_ALLOWED_USERNAMES = [
    username.strip()
    for username in os.getenv("MAINTENANCE_ALLOWED_USERNAMES", "").split(",")
    if username.strip()
]
#Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ['EMAIL_HOST']
EMAIL_PORT = int(os.environ['EMAIL_PORT'])
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']

STORAGE_FOLDER = os.getenv("STORAGE_FOLDER", "")
DASH_FOLDER = os.getenv("DASH_FOLDER", "")
FIREBASE_URL = os.getenv('FIREBASE_URL', '')
FIREBASE_URL_EMA = os.getenv("FIREBASE_URL_EMA", "")
FIREBASE_URL_MAIN = os.getenv("FIREBASE_URL_MAIN", "")
SMTP_SERVER = os.getenv("SMTP_SERVER", EMAIL_HOST)
SMTP_PORT = int(os.getenv("SMTP_PORT", str(EMAIL_PORT)))
SUPPORT_EMAIL = os.getenv("SUPPORT_EMAIL", EMAIL_HOST_USER)
SUPPORT_PWD = os.environ["SUPPORT_PWD"]
SUPPORT_EMAIL_G = os.environ["SUPPORT_EMAIL_G"]
JUSELESS_SERVER = os.getenv('JUSELESS_SERVER', 'juseless.inm7.de')
REMOTE_USERNAME = os.getenv('REMOTE_USERNAME', 'mnarava')
ANALYTICS_PIPELINE_REMOTE_SCRIPT = os.getenv("ANALYTICS_PIPELINE_REMOTE_SCRIPT", "")
ANALYTICS_PIPELINE_SSH_KEY = os.getenv(
    "ANALYTICS_PIPELINE_SSH_KEY",
    "",
)
JUSELESS_SCRIPT_FOLDER = os.getenv('JUSELESS_SCRIPT_FOLDER', '')
JUSELESS_STUDIES_FOLDER = os.getenv('JUSELESS_STUDIES_FOLDER', '')
SERVICE_ACCOUNT_FILE_EMA = os.getenv(
    'SERVICE_ACCOUNT_FILE_EMA',
    str(SECRETS_DIR / '')
) or str(SECRETS_DIR / '')
SERVICE_ACCOUNT_FILE_MAIN = os.getenv(
    'SERVICE_ACCOUNT_FILE_MAIN',
    str(SECRETS_DIR / '')
) or str(SECRETS_DIR / '')
 
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# Enable i18n and localization
USE_I18N = True
LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('de', 'Deutsch'),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = 'Europe/Berlin'

DEFAULT_CHARSET = "utf-8"
X_FRAME_OPTIONS = 'SAMEORIGIN'
SESSION_COOKIE_SAMESITE = "Lax"  # or "Strict"
SESSION_COOKIE_SECURE = True  # Required when SameSite=None

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,  'static')
ADMIN_MEDIA_PREFIX = '/static/admin/'   

CSRF_FAILURE_VIEW = 'jdash.views.csrf_failure'
STATICFILES_FINDERS = (                                                          
     'django.contrib.staticfiles.finders.FileSystemFinder',                       
     'django.contrib.staticfiles.finders.AppDirectoriesFinder',             
  #   'django.contrib.staticfiles.finders.DefaultStorageFinder',
    'django_plotly_dash.finders.DashAssetFinder',  # Critical for Dash components
    'django_plotly_dash.finders.DashComponentFinder',
                   
  )
PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_bootstrap_components',
    'dpd_static_support',  # Required for local assets
]

PLOTLY_DASH = {
    "serve_locally": True,  # Force local file serving
    "cache_arguments": True,  # Required for reliable initial_args
    "cache_timeout_initial_arguments": 300
}
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
LOGIN_URL='/login/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGOUT_REDIRECT_URL = "login"



#session
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
#session
INACTIVE_TIME = 20*60
SESSION_EXPIRE_AT_BROWSER_CLOSE= True
SESSION_COOKIE_AGE = INACTIVE_TIME   # change expired session
SESSION_IDLE_TIMEOUT = INACTIVE_TIME  # logout
SESSION_EXPIRE_SECONDS = INACTIVE_TIME
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = '/login' # Add your URL
USE_TZ = False

