"""
Django settings for admin project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import datetime
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_FILENAME = os.path.join(BASE_DIR,'logs',              
                f"debug_{datetime.datetime.now().strftime('%Y-%m-%d')}.log")



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = False

ALLOWED_HOSTS = [ "127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    "django_browser_reload",
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'dpd_static_support',
    'jdash'
]

MIDDLEWARE = [
    'jdash.middleware.ThreadLocalMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',   
    'django.contrib.messages.middleware.MessageMiddleware',
    'jdash.maintainence_middleware.MaintenanceModeMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
]

ROOT_URLCONF = 'admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'admin.wsgi.application'
ASGI_APPLICATION = 'admin.routing.application'

CRISPY_TEMPLATE_PACK = 'bootstap5'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        'NAME': 'jtrack',
        "USER": "jtrackuser",
        "PASSWORD": "jtrackuser@JDASH123",
        "HOST": "localhost",
        "PORT": "3306",
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
     'filters': {
        'username_filter': {
            '()': 'jdash.logging_filters.UsernameLoggingFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {username} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
        },
    },
    
    'handlers': {
        'file': {
            'level':  'INFO',  # key part!
            'class': 'logging.FileHandler',
            'filename': LOG_FILENAME,
            'formatter': 'verbose',
            'filters': ['username_filter'],
        },
        
    },

    'loggers': {
        'django': {  # root logger: catches all
            'handlers': ['file'],
            'level':  'INFO',  # match the handler
            'propagate': True,
        },
        
    },
}
MAINTENANCE_MODE = False # Set to True to enable maintenance mode
#Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.fz-juelich.de'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
   
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True
DEFAULT_CHARSET = "utf-8"
X_FRAME_OPTIONS = 'SAMEORIGIN'
SESSION_COOKIE_SAMESITE = "Lax"  # or "Strict"
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True  # Required when SameSite=None

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,  'static')
ADMIN_MEDIA_PREFIX = '/static/admin/'   

CSRF_FAILURE_VIEW = 'jdash.views.csrf_failure'
STATICFILES_FINDERS = (                                                          
     'django.contrib.staticfiles.finders.FileSystemFinder',                       
     'django.contrib.staticfiles.finders.AppDirectoriesFinder',             
  #   'django.contrib.staticfiles.finders.DefaultStorageFinder',   
    'django_plotly_dash.finders.DashAssetFinder',  # Critical for Dash components
    'django_plotly_dash.finders.DashComponentFinder',
                   
  )
PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_bootstrap_components',
    'dpd_static_support',  # Required for local assets
]

PLOTLY_DASH = {
    "serve_locally": True,  # Force local file serving
    "cache_arguments": True,  # Required for reliable initial_args
    "cache_timeout_initial_arguments": 300
}
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
LOGIN_URL='/login/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGOUT_REDIRECT_URL = "login"

#session
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
#session
INACTIVE_TIME = 20*60
SESSION_EXPIRE_AT_BROWSER_CLOSE= True
SESSION_COOKIE_AGE = INACTIVE_TIME   # change expired session
SESSION_IDLE_TIMEOUT = INACTIVE_TIME  # logout
SESSION_EXPIRE_SECONDS = INACTIVE_TIME
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = '/login' # Add your URL
